### PR TITLE
update to accept json-ld in <script></script>

### PR DESCRIPTION
**Pull request by Antoine-O**

### CODE REVIEW

**Comment by brent-hoover** [comment]
@Antoine-O Can you explain a little more what this PR does and what you are trying to accomplish with it and how I could test it?

**Comment by Antoine-O** [comment]
Hello @zenweasel !

Sure,
I generate json-ld for spiderable contents and it is actually removed.
see https://developers.google.com/search/docs/guides/intro-structured-data for information about JSON-LD

I get the solution put in production in https://github.com/VeliovGroup/jazeee-meteor-spiderable/issues/42 (see https://github.com/ongoworks/spiderable/issues/10 ) so that json-ld won't be removed :)

you may test it with a page that contains :

```
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Organization",
  "url": "http://www.example.com",
  "name": "Unlimited Ball Bearings Corp.",
  "contactPoint": {
    "@type": "ContactPoint",
    "telephone": "+1-401-555-1212",
    "contactType": "Customer service"
  }
}
</script>

```

**Comment by Antoine-O** [comment]
Any update ?

**Comment by brent-hoover** [comment]
Trying to test this today. Will get back to you as soon as I can

**Comment by Antoine-O** [comment]
thanks mate :)

**Pull request merged**
